#!/bin/bash

scripts/config -d INITRAMFS_SOURCE -d BLK_DEV_INITRD -d DRM_I915 -d BACKLIGHT_CLASS_DEVICE -d SYSTEM_TRUSTED_KEYS -d MODULE_SIG -d CONFIG_MODULE_SIG_ALL  -d CONFIG_MODULE_SIG_FORCE -e HYPERVISOR_GUEST
scripts/config -d IP_NF_TARGET_ECN -d DRM_NOUVEAU -d ACPI_CMPC -d SAMSUNG_Q10

echo "配置完成！"
